<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor handphone atau email</name>
   <tag></tag>
   <elementGuidId>10bf45f9-ca00-4c42-b990-6b5733aa26b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoginID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2aa9257-eb61-433d-80da-e2b2dc263475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>61629fd8-e89a-4f80-aa12-4bdc09a78845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e84e4a7-967c-4fb0-ba39-f8840a2d8e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Nomor handphone atau email</value>
      <webElementGuid>277b2790-8e55-4211-8538-7ac1b3e40140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginID</value>
      <webElementGuid>0a71a80b-08a0-4c0e-b51a-612a6ccb3d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-text-field__input</value>
      <webElementGuid>259d0603-51d1-46ad-bc88-97f720d38072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginID&quot;)</value>
      <webElementGuid>c4bb7a5b-0088-42f0-af62-c49866819719</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginID']</value>
      <webElementGuid>204c8b5b-1cca-4f80-b170-ba1e7290bf29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5458e35d-ed8f-41b0-b418-9a066164ba72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'LoginID']</value>
      <webElementGuid>f92e839a-7395-4c40-a3c1-51d5a0860b17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
